name: Publish to GitHub Package Repository

on:
  push:
    branches:
      - main
    paths:
      - 'gradle/libs.versions.toml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/wrapper-validation-action@v3.5.0
      - uses: gradle/gradle-build-action@v3.5.0
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          arguments: --configuration-cache generateCatalogAsToml

      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M).$(git rev-parse --short=12 HEAD)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          generateReleaseNotes: true
          makeLatest: true # Versjonnummerene er ikke semantiske

      - name: publish
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_version: ${{ env.RELEASE_TAG }}
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }